//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement.EntityLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblLogin
    {
        public int Id { get; set; }
        [DataType(DataType.EmailAddress,ErrorMessage = "Incorrect Email format !")]
        [Required(ErrorMessage = "Email is Required !")]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Email is not valid.")]
        public string Username { get; set; }
        
        [Required(ErrorMessage = "Password is Required !")]
        public string Password { get; set; }
    }
}
